debug: true
server:
  port: 8766
    
spring:
  application:
    name: jwt
  profiles:
    active: dev
    include: 
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: test
    username: user
    password: gdsftest2014
    url: jdbc:mysql://10.1.12.221:3306/test?zeroDateTimeBehavior=CONVERT_TO_NULL
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
