debug: false

logging:
  config: classpath:logback.xml
  
spring:
  application:
    name: demo
    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    name: test
    username: user
    password: gdsftest2014
    url: jdbc:mysql://10.1.12.221:3306/test?zeroDateTimeBehavior=convertToNull
    druid:
      initial-size: 5
      max-active: 15
      min-idle: 10
      max-wait: 5000
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
              
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      
#  security:
#    user:
#      name: user
#      password: 123
    
  http:
    encoding:
      charset: UTF-8
      
  profiles:
    active: dev12
    include: 
    
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enable-spring-el-compiler: false
    enabled: true
    encoding: UTF-8
    view-names: test
    excluded-view-names: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
